### ISSUE TITLE
Ability to lock/unlock/constrain  individual objects on the fly

### ISSUE THREAD

**Issue by patmo141** [bblanimation/interactive-physics-editor#3]
As the objects are arranged, we need to be able to lock or unlock an objects position/rotation in the scene.   It might also be nice to allow "flexible" locking (via constraints). Constraints are also a good avenue to use take because they can be used to constrain the object to it's local axes.

Lock Position
Constrain Position within tolerance, x, y, z
Lock Rotation
Constrain Rotation within tolerance x, y, z

**Comment by bblanimation** [comment]
This feature was implemented in commits 9261ebd and eebf652
