### ISSUE TITLE
ghost movement

### ISSUE THREAD

**Issue by patmo141** [bblanimation/interactive-physics-editor#4]
https://youtu.be/MSwQaWHxnPU

looks like perhaps a tooth is being moved in the sim, but then reset by the handler before the scene update making it look like ghost movement?  Unsure on this one.

-P

**Comment by bblanimation** [comment]
I'm not able to recreate this issue on my end – are you still running into this issue on the master branch?

**Comment by patmo141** [comment]
I have not run into this issue in a while, I think we can close it and if it reappears, then open it.
