### ISSUE TITLE
[Suggestion]I have some ideas.

### ISSUE THREAD

**Issue by actcathorse** [bblanimation/interactive-physics-editor#5]
Hello bblanimation,
The tool is very creative.^_^(I buy it )
I hope i can use transform gizmo in interactive mode.
That will be more precise.
I hope Gravity value can be adjust.
Sometime Gravity(9.8m/s2) is too slow.
I hope this tool is getting better and better.

**Comment by bblanimation** [comment]
Thank you for your suggestions, and for buying the tool! I've addressed these suggestions in commits 49cc9cf (transform gismo) and 3df8259 (gravity control).
