### ISSUE TITLE
Plugin not listed after install on Blender 2.8

### ISSUE THREAD

**Issue by Fubaxiusz** [bblanimation/interactive-physics-editor#6]
After successful installation plugin is not listed in the plugin tab, thus impossible to enable.

**Comment by Fubaxiusz** [comment]
I figured out the issue. Addon is installed in folder named 
`interactive-physics-editor-1.1.1`
changing it into
`interactive-physics-editor`
fixes the issue

**Comment by bblanimation** [comment]
Thank you for reporting this issue! I'm glad you were able to identify the problem.
