### ISSUE TITLE
I did not think it would work for curves, but decided to try anyway.

### ISSUE THREAD

**Issue by scurv** [bblanimation/interactive-physics-editor#9]
I've got some soft body modeling to do and I decided to see if this would handle curves. I did not think it would, but meh, why not try anyway. Still though, it is a nice addon for making cluttered rooms.

Please copy the following form and paste it into a new issue at https://github.com/bblanimation/interactive-physics-editor/issues

Don't forget to include a description of your problem! The more information you provide (what you were trying to do, what action directly preceeded the error, etc.), the easier it will be for us to squash the bug.

### COPY EVERYTHING BELOW THIS LINE ###

Description of the Problem:

Blender Version: 002.081.000
Addon Version: 1, 1, 2
Platform Info:
   system   = Windows
   platform = Windows-10-10.0.17763
   version  = 10.0.17763
   python   = 3.7.0
Error:
EXCEPTION (<class 'RuntimeError'>): Operator bpy.ops.rigidbody.objects_add.poll() failed, context is incorrect
         C:\Users\Josep\Desktop\blender-2.81.0-git.81a29b8c9e57-windows64\2.81\scripts\modules\bpy\ops.py
000 0201:__call__() ret = op_call(self.idname_py(), None, kw)
         C:\Users\Josep\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\interactive_physics_editor_1_1_2\operators\setup_phys.py
001 0172:set_up_physics() bpy.ops.rigidbody.objects_add()
002 0096:execute() self.set_up_physics()

**Comment by bblanimation** [comment]
Thank you for bringing this to my attention! Yes, the addon sadly cannot handle non-mesh objects, as it relies on Blender's internal Rigid Body Physics engine. I've addressed this so that in the next release, an attempt to initialize the editor with non-mesh objects will warn the user gracefully, as opposed to throwing an error.
